from __future__ import annotations

from pathlib import Path

import pytest
from lxml import etree

from backend.app.pdm import (
    delete_pdm_tables,
    file_sha256,
    parse_pdm,
    update_pdm_dictionary,
    update_pdm_fields,
)


SAMPLE_PDM = """<?xml version="1.0" encoding="UTF-8"?>
<?PowerDesigner Name="测试模型" Target="ORACLE Version 11g" version="15.1.0.2850"?>
<!-- do not edit this file -->
<Model xmlns:a="attribute" xmlns:c="collection" xmlns:o="object">
  <o:RootObject Id="o1">
    <c:Children>
      <o:Model Id="o2">
        <a:Name>测试模型</a:Name>
        <c:Tables>
          <o:Table Id="o10">
            <a:Name>用户表</a:Name>
            <a:Code>t_user</a:Code>
            <a:Comment>保存系统用户</a:Comment>
            <c:Columns>
              <o:Column Id="o11">
                <a:Name>用户编号</a:Name>
                <a:Code>user_id</a:Code>
                <a:DataType>NUMBER(20)</a:DataType>
                <a:Length>20</a:Length>
                <a:Mandatory>1</a:Mandatory>
                <a:Comment>全局唯一编号</a:Comment>
              </o:Column>
              <o:Column Id="o12">
                <a:Name>用户名称</a:Name>
                <a:Code>user_name</a:Code>
                <a:DataType>VARCHAR2(64)</a:DataType>
                <a:Length>64</a:Length>
                <a:DefaultValue>'匿名'</a:DefaultValue>
              </o:Column>
            </c:Columns>
            <c:Keys>
              <o:Key Id="o20">
                <c:Key.Columns><o:Column Ref="o11" /></c:Key.Columns>
              </o:Key>
            </c:Keys>
            <c:PrimaryKey><o:Key Ref="o20" /></c:PrimaryKey>
          </o:Table>
        </c:Tables>
      </o:Model>
    </c:Children>
  </o:RootObject>
</Model>
"""


def write_sample(path: Path) -> Path:
    path.write_text(SAMPLE_PDM, encoding="utf-8", newline="\n")
    return path


def test_parse_powerdesigner_dictionary(tmp_path: Path) -> None:
    source = write_sample(tmp_path / "sample.pdm")

    parsed = parse_pdm(source)

    assert parsed.model_name == "测试模型"
    assert parsed.pd_version == "15.1.0.2850"
    assert parsed.target_db == "ORACLE Version 11g"
    assert len(parsed.tables) == 1
    assert parsed.field_count == 2
    table = parsed.tables[0]
    assert (table.name, table.code, table.comment) == ("用户表", "t_user", "保存系统用户")
    assert table.fields[0].is_primary_key is True
    assert table.fields[0].nullable is False
    assert table.fields[0].data_type == "NUMBER"
    assert table.fields[0].length == "20"
    assert table.fields[1].default_value == "'匿名'"


def test_update_fields_preserves_valid_pdm(tmp_path: Path) -> None:
    source = write_sample(tmp_path / "source.pdm")
    destination = tmp_path / "updated.pdm"
    source_hash = file_sha256(source)

    update_pdm_fields(
        source,
        destination,
        {
            "o12": {
                "name": "登录名称",
                "code": "login_name",
                "data_type": "VARCHAR2",
                "length": "96",
                "nullable": False,
                "default_value": "",
                "comment": "由码熊更新",
            }
        },
    )

    parsed = parse_pdm(destination)
    field = parsed.tables[0].fields[1]
    assert field.name == "登录名称"
    assert field.code == "login_name"
    assert field.length == "96"
    assert field.nullable is False
    assert field.comment == "由码熊更新"
    assert file_sha256(source) == source_hash


def test_update_table_metadata_preserves_valid_pdm(tmp_path: Path) -> None:
    source = write_sample(tmp_path / "source.pdm")
    destination = tmp_path / "updated.pdm"

    updated_tables, updated_fields = update_pdm_dictionary(
        source,
        destination,
        {
            "o10": {
                "name": "账户用户表",
                "code": "t_account_user",
                "comment": "保存账户用户及其状态",
            }
        },
        {},
    )

    table = parse_pdm(destination).tables[0]
    assert (updated_tables, updated_fields) == (1, 0)
    assert (table.name, table.code, table.comment) == (
        "账户用户表",
        "t_account_user",
        "保存账户用户及其状态",
    )


def test_add_and_delete_unreferenced_field(tmp_path: Path) -> None:
    source = write_sample(tmp_path / "source.pdm")
    destination = tmp_path / "updated.pdm"

    update_pdm_dictionary(
        source,
        destination,
        {},
        {},
        field_additions_by_table_xml_id={
            "o10": [
                {
                    "name": "电子邮箱",
                    "code": "email",
                    "data_type": "VARCHAR2",
                    "length": "128",
                    "nullable": True,
                    "default_value": "",
                    "comment": "登录邮箱",
                }
            ]
        },
        field_deletions_by_xml_id={"o12"},
    )

    fields = parse_pdm(destination).tables[0].fields
    assert [field.code for field in fields] == ["user_id", "email"]
    assert fields[1].xml_id.startswith("o")
    assert fields[1].xml_id[1:].isdigit()
    assert fields[1].length == "128"
    assert fields[1].comment == "登录邮箱"
    tree = etree.parse(str(destination))
    new_column = next(
        node for node in tree.getroot().iter("{object}Column") if node.get("Id") == fields[1].xml_id
    )
    attributes = {
        etree.QName(child.tag).localname: child.text or ""
        for child in new_column
        if isinstance(child.tag, str) and child.tag.startswith("{attribute}")
    }
    assert len(attributes["ObjectID"]) == 36
    assert attributes["CreationDate"].isdigit()
    assert attributes["Creator"]


def test_delete_referenced_field_is_blocked(tmp_path: Path) -> None:
    source = write_sample(tmp_path / "source.pdm")
    with pytest.raises(ValueError, match="引用"):
        update_pdm_dictionary(
            source,
            tmp_path / "updated.pdm",
            {},
            {},
            field_deletions_by_xml_id={"o11"},
        )


def test_delete_table_removes_table_symbol(tmp_path: Path) -> None:
    source = write_sample(tmp_path / "source.pdm")
    content = source.read_text(encoding="utf-8").replace(
        "      </o:Model>",
        """        <c:Symbols>
          <o:TableSymbol Id="o30"><c:Object><o:Table Ref="o10" /></c:Object></o:TableSymbol>
        </c:Symbols>
      </o:Model>""",
    )
    source.write_text(content, encoding="utf-8", newline="\n")
    destination = tmp_path / "deleted.pdm"

    result = delete_pdm_tables(source, destination, {"o10"})

    assert result == {"table_count": 1, "field_count": 2, "reference_count": 0}
    assert parse_pdm(destination).tables == ()
    assert "TableSymbol" not in destination.read_text(encoding="utf-8")
